# Generated by Django 6.0.7 on 2026-08-05 09:47

import cloudinary.models
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logos')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DELETE_ACCOUNT', 'Delete Account'), ('CHANGE_PASSWORD', 'Change Password'), ('CHANGE_EMAIL', 'Change Email'), ('CHANGE_PHONE', 'Change Phone'), ('SENSITIVE_ACTION', 'Sensitive Action')], max_length=50)),
                ('method', models.CharField(choices=[('EMAIL_OTP', 'Email OTP'), ('PASSWORD', 'Password')], max_length=30)),
                ('challenge_id', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
