# Generated by Django 6.0.7 on 2026-08-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='verificationchallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True), ('expired', False), ('verified_at__isnull', True)), fields=('user', 'action'), name='unique_active_challenge_per_user_action'),
        ),
    ]
