# Generated by Django 6.0.7 on 2026-08-05 09:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_body', models.TextField()),
                ('post_title_color', models.CharField(default='#000000', max_length=15)),
                ('post_img', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='blognet/post_img')),
                ('post_category', models.CharField(choices=[('food', 'Food'), ('electronics', 'Electronics'), ('life_hacks', 'Life Hacks'), ('family', 'Family'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('stories', 'Stories'), ('news', 'News')], default='food', max_length=20)),
                ('like', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_liked', models.BooleanField(default=True)),
            ],
        ),
    ]
