# Generated by Django 6.0.7 on 2026-08-03 03:34

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_likepost_is_liked'),
        ('user', '0002_profile_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='post_catagory',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='post_category',
            field=models.CharField(choices=[('food', 'Food'), ('electronics', 'Electronics'), ('life_hacks', 'Life Hacks'), ('family', 'Family'), ('education', 'Education'), ('entertainment', 'Entertainment'), ('stories', 'Stories'), ('news', 'News')], default='food', max_length=20),
        ),
        migrations.AddField(
            model_name='comments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='post_img/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_title_color',
            field=models.CharField(default='#000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blogpost'),
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('post', 'profile')},
        ),
    ]
